[package]
name = "Cards"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
lazy_static = "1.5.0"
rand = "0.9.1"
uuid = { version = "1.16.0", features = ["v4"] }
